name: Test

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create network
      run: docker network create web || true

    - name: Start containers
      run: docker compose -f "docker-compose.yml" up -d --build

    - name: Check containers
      run: docker container ps

    - name: Check containers
      run: docker network inspect web

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" down -v --rmi all
    
    - name: Scan with sqlmap
      uses: thereisnotime/action-sqlmap@master
        with:
          url: "http://172.18.0.3"
          additional_args: "--batch --crawl=2 --random-agent --forms --level=5 --risk=3"